### ISSUE TITLE
jwt.encode is not encrypted.. just serialized and signed.

### ISSUE THREAD

**Issue by whardier** [MedAmineFouzai/GameShop_Backend#1]
https://github.com/MedAmineFouzai/GameShop_Backend/blob/001f8c2778dfcbfbd36300b2f9001287883f10fb/controllers/handlers.py#L112

Note to not put passwords in JWT tokens as a rule of thumb.  Was reviewing your code looking for some useful examples of PyJWT in production.

**Comment by AmineFouzai** [comment]
thank you @whardier  for your review ill fix it son ,thanks agin a lot
